name: Deploy  #Naming the action

on:
  push:
    branches:
      - main   #When pushing, pushing main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} #The secret keys have been saved in Secrets
          heroku_app_name: "final-projectjulien" #Must be unique in Heroku
          heroku_email: "julien.maalouf@hotmail.fr"
